name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true

  deploy:
    needs: [test]
    runs-on: ubuntu-22.04

    steps:
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        # Adding your server's host to known_hosts
        echo "Adding SSH host to known_hosts"
        ssh-keyscan -H "18.219.222.44" >> ~/.ssh/known_hosts  # Your server's IP

    - name: SSH and deploy node app
      run: |
        SSH_HOST="18.219.222.44"  # Your server's IP address
        SSH_USERNAME="ubuntu"  # Your SSH username
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << 'EOF'
          cd /var/www/html/cicd
          git pull origin main
          npm install --production
          pm2 restart cicd-test
        EOF
